function(bssas_require_existing_path path description)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "${description} is missing from ${path}")
    endif()
endfunction()

function(bssas_collect_existing_paths out_var base_dir description)
    set(result "")
    foreach(item IN LISTS ARGN)
        set(path "${base_dir}/${item}")
        if(NOT EXISTS "${path}")
            message(FATAL_ERROR "Required ${description} is missing from ${path}")
        endif()
        list(APPEND result "${path}")
    endforeach()
    set(${out_var} "${result}" PARENT_SCOPE)
endfunction()

function(bssas_require_defined variable_name)
    if(NOT DEFINED ${variable_name})
        message(FATAL_ERROR "${variable_name} is required")
    endif()
endfunction()
